In [1]:
import numpy as np

넘파이 객체 생성 및 속성들  
np.array 함수  


In [43]:
list1 = [1.,2,3,4,5,6]

In [44]:
arr = np.array(list1)

In [46]:
arr =arr.reshape(3,2)

In [31]:
array1 = np.array(list1)

In [36]:
array2 = np.array([1,'a',2.])

In [38]:
type(array2)

numpy.ndarray

In [47]:
array3 = np.zeros((2,3),int)

In [48]:
array3

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
array4 = np.full((5,5),255,int)

In [51]:
array4 = np.identity(5)

In [52]:
array4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
array1 = np.arange(0,100,2)

In [62]:
type(array1)

numpy.ndarray

In [63]:
array1.shape

(50,)

In [65]:
array1=array1.reshape(5,10)

In [66]:
array1

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [72]:
array0 = np.full((3,2),None)

In [73]:
array0

array([[None, None],
       [None, None],
       [None, None]], dtype=object)

In [78]:
array0.flatten()

array([None, None, None, None, None, None], dtype=object)